# Generated by Django 3.1.6 on 2021-05-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='Name',
            field=models.CharField(max_length=50),
        ),
    ]
