# Generated by Django 3.1.6 on 2021-05-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20210529_0435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('url', models.TextField(max_length=254)),
                ('date', models.DateTimeField()),
                ('time', models.CharField(max_length=50)),
            ],
        ),
    ]
