# Generated by Django 3.1.6 on 2021-05-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
