# Generated by Django 3.1.6 on 2021-05-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_auto_20210529_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar',
            name='DOB',
        ),
        migrations.AddField(
            model_name='seminar',
            name='age',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
