# Generated by Django 3.1.7 on 2021-07-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='slug',
            field=models.SlugField(default='SOME STRING', max_length=1000),
        ),
    ]
